#!/usr/bin/python
# Autogenerated DFA code using fsm-code-designer

import sys

def step(label, c):
	'''
	Finds the next label to be accessed while
	stepping through the DFA.
	@param label: the current label/state the DFA is on
	@param c: the next read character
	'''
	if c == '0' and label == '0':
		return '1'
	if c == '0' and label == '1':
		return '0'
	if c == '1' and label == '0':
		return '1'
	if c == '1' and label == '1':
		return '0'
	sys.exit('invalid label')


def run(string):
	'''
	Runs the given DFA on a certain string.
	@param string: the string to run the DFA on
	'''
	state = '0'
	for c in string:
		state = step(state, c)
	return state in ['0']


if __name__ == '__main__':
	if len(sys.argv) <= 1:
		sys.exit('No string provided to run against.')
	print(run(sys.argv[1]))
